# Generated by Django 5.1.9 on 2025-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_app', models.DateField(auto_now_add=True)),
                ('updated_app', models.DateField(auto_now=True)),
            ],
        ),
    ]
