# Generated by Django 5.1.9 on 2025-05-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Tenant',
        ),
    ]
