# Generated by Django 5.1.9 on 2025-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tanentaddress_tanentemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanentaddress',
            name='old_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanentaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
