# Generated by Django 5.1.9 on 2025-05-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployee',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tenant'),
        ),
    ]
