# Generated by Django 5.1.9 on 2025-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tanentaddress_old_id_alter_tanentaddress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanentemployee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
