# Generated by Django 5.1.9 on 2025-05-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tanentemployee_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TanentAddress',
            new_name='TenantAddress',
        ),
        migrations.RenameModel(
            old_name='TanentEmployee',
            new_name='TenantEmployee',
        ),
    ]
