# Generated by Django 5.1.9 on 2025-05-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.address')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.employee')),
            ],
        ),
    ]
