# Generated by Django 5.1.9 on 2025-05-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_employeeaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAddress',
        ),
    ]
